---
- name: Installing the dependencies for the server
  apt: 
    name: "{{ item }}"
    state: present
  with_items: [ "apache2", "ghostscript", "libapache2-mod-php", "mysql-server", "php", "php-bcmath", "php-curl", "php-imagick", "php-intl", "php-json", "php-mbstring", "php-mysql", "php-xml", "php-zip" , "python3-mysqldb" ]

- name: Creating a directory for the wordpress
  file: 
    path: /srv/www/
    state: directory
    mode: "0755"
    owner: www-data
    group: www-data

- name: Configuring the apache for the wordpress
  template: 
    src: virtualhost.tmpl
    dest: /etc/apache2/sites-available/wordpress.conf

- name: Enabling wordpress site
  shell: a2ensite wordpress

- name: Enabling the apache module
  apache2_module:
    name: rewrite
    state: present

- name: Dissabling the default it works site with
  shell: a2dissite 000-default

- name: starting the apache any mysql service.
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - apache2
    - mysql

